//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIESECJournal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDaily
    {
        public short Id { get; set; }
        public string Event { get; set; }
        public string Goal { get; set; }
        public string SuccessStory { get; set; }
        public string FailureStory { get; set; }
        public string Note { get; set; }
    }
}
